PRAGMA foreign_keys=ON;
CREATE TABLE source_policy_versions (source_id TEXT NOT NULL, version TEXT NOT NULL, configuration_hash TEXT NOT NULL, policy_json TEXT NOT NULL, recorded_at TEXT NOT NULL, PRIMARY KEY(source_id,version));
CREATE TABLE sources (source_id TEXT PRIMARY KEY, policy_version TEXT NOT NULL, enabled INTEGER NOT NULL, config_json TEXT NOT NULL, suspended INTEGER NOT NULL DEFAULT 0, consecutive_failures INTEGER NOT NULL DEFAULT 0, circuit_until TEXT, last_success_at TEXT, last_artifact_ref TEXT, last_count INTEGER NOT NULL DEFAULT 0);
CREATE TABLE collection_runs (run_id TEXT PRIMARY KEY, source_id TEXT NOT NULL, scheduled_for TEXT NOT NULL, state TEXT NOT NULL, lease_token TEXT, lease_until TEXT, started_at TEXT, finished_at TEXT, artifact_ref TEXT, observation_count INTEGER DEFAULT 0, accepted_count INTEGER DEFAULT 0, error_code TEXT, next_attempt_at TEXT, recovery_count INTEGER NOT NULL DEFAULT 0, metrics_json TEXT, UNIQUE(source_id,scheduled_for));
CREATE INDEX runs_pending ON collection_runs(state,scheduled_for);
CREATE TABLE fetch_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, run_id TEXT NOT NULL REFERENCES collection_runs, attempt INTEGER NOT NULL, started_at TEXT NOT NULL, status INTEGER, code TEXT NOT NULL, duration_ms INTEGER NOT NULL);
CREATE TABLE raw_artifacts (artifact_ref TEXT PRIMARY KEY, source_id TEXT NOT NULL, run_id TEXT NOT NULL REFERENCES collection_runs, observed_at TEXT NOT NULL, payload_hash TEXT NOT NULL, evidence_hash TEXT NOT NULL, bytes INTEGER NOT NULL, expires_at TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'retained');
CREATE TABLE observations (observation_id TEXT PRIMARY KEY, source_id TEXT NOT NULL, policy_version TEXT NOT NULL, run_id TEXT NOT NULL REFERENCES collection_runs, dataset TEXT NOT NULL CHECK(dataset IN ('fx','ai_api_prices')), entity_key TEXT NOT NULL, observed_at TEXT NOT NULL, recorded_at TEXT NOT NULL, fingerprint TEXT NOT NULL, parser_version TEXT NOT NULL, quality_status TEXT NOT NULL, supersedes_observation_id TEXT REFERENCES observations, metadata_json TEXT NOT NULL, UNIQUE(run_id,entity_key,parser_version,policy_version,fingerprint));
CREATE INDEX observation_series ON observations(source_id,entity_key,observed_at DESC,recorded_at DESC);
CREATE INDEX observation_content ON observations(source_id,entity_key,fingerprint,recorded_at);
CREATE TABLE fx_observations (observation_id TEXT PRIMARY KEY REFERENCES observations, base_currency TEXT NOT NULL, quote_currency TEXT NOT NULL, rate_decimal TEXT NOT NULL, source_date TEXT NOT NULL, domain_json TEXT NOT NULL);
CREATE INDEX fx_date ON fx_observations(source_date,base_currency,quote_currency);
CREATE TABLE ai_api_prices (observation_id TEXT PRIMARY KEY REFERENCES observations, serving_provider TEXT, model_id TEXT NOT NULL, domain_json TEXT NOT NULL);
CREATE INDEX ai_provider_model ON ai_api_prices(serving_provider,model_id);
CREATE TRIGGER immutable_observations BEFORE UPDATE ON observations BEGIN SELECT RAISE(ABORT,'append-only observations'); END;
CREATE TRIGGER immutable_fx BEFORE UPDATE ON fx_observations BEGIN SELECT RAISE(ABORT,'append-only FX'); END;
CREATE TRIGGER immutable_ai BEFORE UPDATE ON ai_api_prices BEGIN SELECT RAISE(ABORT,'append-only AI prices'); END;
CREATE TABLE quality_events (event_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES collection_runs, record_key TEXT, code TEXT NOT NULL, recorded_at TEXT NOT NULL);
CREATE TABLE change_events (event_id TEXT PRIMARY KEY, observation_id TEXT NOT NULL REFERENCES observations, previous_observation_id TEXT NOT NULL REFERENCES observations, dataset TEXT NOT NULL, entity_key TEXT NOT NULL, observed_at TEXT NOT NULL, details_json TEXT NOT NULL);
CREATE TABLE derived_observations (observation_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES collection_runs, dataset TEXT NOT NULL, entity_key TEXT NOT NULL, observed_at TEXT NOT NULL, recorded_at TEXT NOT NULL, methodology_version TEXT NOT NULL, value_json TEXT NOT NULL);
CREATE TABLE lineage (observation_id TEXT NOT NULL REFERENCES derived_observations, input_observation_id TEXT NOT NULL REFERENCES observations, PRIMARY KEY(observation_id,input_observation_id));
CREATE TABLE daily_summaries (summary_id TEXT PRIMARY KEY, recorded_at TEXT NOT NULL, summary_json TEXT NOT NULL);
CREATE TABLE notification_outbox (notification_id TEXT PRIMARY KEY, payload_json TEXT NOT NULL, state TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, recorded_at TEXT NOT NULL, last_attempt_at TEXT, sent_at TEXT);
